name: automation-ui-test-run
on:
  push:
    paths:
      - 'src/test/**'
  schedule:
    - cron: '0 9 * * 1,4'
jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Gradle
        run: ./gradlew -Dtags="regression" -Dscreenshots="serenity" -Dwebdriver.driver="chrome" -Dchrome.switches="--window-size=1920,1080;--headless;"
      - name: Automation ui test result
        uses: actions/upload-artifact@v2
        with:
          name: automation-ui-test-result
          path: target/site
          retention-days: 3