name: automation-ui-test-run
on:
  push:
    paths:
      - 'src/test/**'
  schedule:
    - cron: '0 9 * * 1,4'
jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Gradle
        run: ./gradlew -DincludeTags="regression" -Ddriver="chrome" -DdriverArguments="--headless=new;--window-size=1920,1080;"
      - name: Automation ui test result
        uses: actions/upload-artifact@v2
        with:
          name: selenium-ui-test-result
          path: build/reports/tests/test
          retention-days: 3