name: automation-ui-test-run
on:
  push:
    paths:
      - 'src/test/**'
  schedule:
    - cron: '0 9 * * 1,4'
jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          architecture: x64
      - name: Gradle run
        run: ./gradlew -DincludeTags="regression" -Ddriver="chrome" -DdriverArguments="--headless=new;--window-size=1920,1080;"
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: build/allure-results
      - name: Automation ui test result
        uses: actions/upload-artifact@v4
        with:
          name: selenium-ui-test-result
          path: allure-report
          retention-days: 3