name: automation-ui-test-run
on:
  push:
    paths:
      - 'src/test/**'
  schedule:
    - cron: '0 9 * * 1,4'
jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Get preinstalled chrome version
        id: get_chrome_version
        run: |
          CHROME_VERSION_FULL=$(google-chrome --version | awk '{print $3}')
          echo "Complete Chrome preinstalled version: $CHROME_VERSION_FULL"
          echo "chrome_version=$CHROME_VERSION_FULL" >> $GITHUB_OUTPUT
      - name: Configure corresponding Chrome and ChromeDriver version
        id: setup_chrome_driver
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: ${{ steps.get_chrome_version.outputs.chrome_version }}
          install-chromedriver: true
      - name: Gradle run
        run: ./gradlew -DincludeTags="regression" -Ddriver="chrome" -DdriverArguments="--incognito --headless=new --window-size=1920,1080"
      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history